version: '3.4'

services:
  motivator:
    image: ${DOCKER_REGISTRY-}motivator
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: Motivator
      PGDATA: E:/Motivator/PGDATA
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
